-- Profil expert complet pour Kabunda Fabien (user_id: 195ab38f-51ed-495c-99c9-421ebcd6caaf)
INSERT INTO user_accountant_profiles (
  id,
  user_id,
  company_name,
  registration_number,
  specialization,
  experience_years,
  country,
  province,
  city,
  address,
  professional_email,
  professional_phone,
  website,
  profile_photo_url,
  is_available,
  max_companies,
  total_companies_managed,
  active_companies_count,
  rating,
  total_reviews,
  bio,
  certifications,
  languages,
  linkedin_url,
  business_hours,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid()::text,
  '195ab38f-51ed-495c-99c9-421ebcd6caaf',
  'FBG Consult',
  'OEC-RDC-2024-001',
  ARRAY['Comptabilité générale', 'Fiscalité', 'TVA', 'Audit', 'Conseil aux PME', 'Déclarations fiscales'],
  12,
  'RDC',
  'Kinshasa',
  'Kinshasa',
  'Avenue du Commerce, Gombe, Kinshasa',
  'expertcomptable@fbgconsult.com',
  '+243 812 345 678',
  'https://www.fbgconsult.com',
  NULL,
  true,
  25,
  0,
  0,
  0,
  0,
  'Cabinet d''expertise comptable et de conseil au service des entreprises en RDC. Nous accompagnons les PME et TPE dans leur développement avec une offre complète : tenue de comptabilité, déclarations fiscales et sociales, audit et conseil. Équipe expérimentée et à l''écoute de vos besoins.',
  ARRAY['OEC (Ordre des Experts-Comptables)', 'Expert-comptable agréé RDC', 'Certification audit'],
  ARRAY['Français', 'Anglais', 'Lingala'],
  'https://linkedin.com/in/kabunda-fabien',
  'Lun–Ven 8h–18h, sur rendez-vous le samedi',
  NOW(),
  NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  registration_number = EXCLUDED.registration_number,
  specialization = EXCLUDED.specialization,
  experience_years = EXCLUDED.experience_years,
  country = EXCLUDED.country,
  province = EXCLUDED.province,
  city = EXCLUDED.city,
  address = EXCLUDED.address,
  professional_email = EXCLUDED.professional_email,
  professional_phone = EXCLUDED.professional_phone,
  website = EXCLUDED.website,
  is_available = EXCLUDED.is_available,
  max_companies = EXCLUDED.max_companies,
  bio = EXCLUDED.bio,
  certifications = EXCLUDED.certifications,
  languages = EXCLUDED.languages,
  linkedin_url = EXCLUDED.linkedin_url,
  business_hours = EXCLUDED.business_hours,
  updated_at = NOW();
