import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../../.env') });
const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: parseInt(process.env.PORT || '3001', 10),
  BACKEND_URL: process.env.BACKEND_URL || 'http://localhost:3001',
  FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:3000',
  DATABASE_URL: process.env.DATABASE_URL || '',
  DATABASE_READ_URL: process.env.DATABASE_READ_URL || '',
  JWT_SECRET: process.env.JWT_SECRET || 'secret',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '15m',
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'refresh_secret',
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
  BCRYPT_ROUNDS: parseInt(process.env.BCRYPT_ROUNDS || '10', 10),
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || '',
  REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
  REDIS_ENABLED: process.env.REDIS_ENABLED === 'true',
  REDIS_DISABLED: process.env.REDIS_DISABLED === 'true',
  REDIS_HOST: process.env.REDIS_HOST || 'localhost',
  REDIS_PORT: parseInt(process.env.REDIS_PORT || '6379', 10),
  REDIS_PASSWORD: process.env.REDIS_PASSWORD || '',
  SMTP_HOST: process.env.SMTP_HOST || 'localhost',
  SMTP_PORT: parseInt(process.env.SMTP_PORT || '587', 10),
  SMTP_SECURE: process.env.SMTP_SECURE === 'true',
  SMTP_USER: process.env.SMTP_USER || '',
  SMTP_PASS: process.env.SMTP_PASS || '',
  SMTP_FROM: process.env.SMTP_FROM || 'noreply@conta.cd',
  SMTP_NOTIF_FROM: process.env.SMTP_NOTIF_FROM || 'notifications@conta.cd',
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL || 'support@conta.cd',
  PAYPAL_ENABLED: process.env.PAYPAL_ENABLED === 'true',
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID || '',
  PAYPAL_SECRET_KEY: process.env.PAYPAL_SECRET_KEY || '',
  PAYPAL_MODE: process.env.PAYPAL_MODE || 'sandbox',
  PAYPAL_WEBHOOK_ID: process.env.PAYPAL_WEBHOOK_ID || '',
  WHATSAPP_META_ACCESS_TOKEN: process.env.WHATSAPP_META_ACCESS_TOKEN || '',
  WHATSAPP_META_PHONE_NUMBER_ID: process.env.WHATSAPP_META_PHONE_NUMBER_ID || '',
  WHATSAPP_META_GRAPH_VERSION: process.env.WHATSAPP_META_GRAPH_VERSION || 'v18.0',
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: process.env.WHATSAPP_WEBHOOK_VERIFY_TOKEN || '',
  WHATSAPP_API_KEY: process.env.WHATSAPP_API_KEY || '',
  WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET || '',
  MAXICASH_API_URL: process.env.MAXICASH_API_URL || '',
  MAXICASH_API_KEY: process.env.MAXICASH_API_KEY || '',
  MAXICASH_MERCHANT_ID: process.env.MAXICASH_MERCHANT_ID || '',
  AIRTEL_CLIENT_ID: process.env.AIRTEL_CLIENT_ID || '',
  AIRTEL_CLIENT_SECRET: process.env.AIRTEL_CLIENT_SECRET || '',
  AIRTEL_SANDBOX: process.env.AIRTEL_SANDBOX === 'true',
  MPESA_CONSUMER_KEY: process.env.MPESA_CONSUMER_KEY || '',
  MPESA_CONSUMER_SECRET: process.env.MPESA_CONSUMER_SECRET || '',
  MPESA_SHORTCODE: process.env.MPESA_SHORTCODE || '',
  MPESA_PASSKEY: process.env.MPESA_PASSKEY || '',
  MPESA_SANDBOX: process.env.MPESA_SANDBOX === 'true',
  VAPID_PUBLIC_KEY: process.env.VAPID_PUBLIC_KEY || '',
  VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY || '',
  VAPID_SUBJECT: process.env.VAPID_SUBJECT || 'mailto:support@conta.cd',
  UPLOAD_DIR: process.env.UPLOAD_DIR || 'uploads',
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  CRON_SECRET: process.env.CRON_SECRET || '',
  ACCOUNT_DELETION_GRACE_PERIOD_DAYS: parseInt(process.env.ACCOUNT_DELETION_GRACE_PERIOD_DAYS || '30', 10),
  ACCOUNT_ANONYMIZATION_PERIOD_DAYS: parseInt(process.env.ACCOUNT_ANONYMIZATION_PERIOD_DAYS || '90', 10),
  config: {
    isProduction: process.env.NODE_ENV === 'production',
    isDevelopment: process.env.NODE_ENV === 'development',
  },
};
export default env;
